apiVersion: skaffold/v4beta9
kind: Config
metadata:
  name: k8s-test
build:
  artifacts:
    - image: 52.14.78.29:5001/k8s-test
      docker:
        dockerfile: Dockerfile
deploy:
  kubectl:
    defaultNamespace: default
manifests:
  rawYaml:
    - ./k8s/*
profiles:
  - name: build
    build:
      local:
        useBuildkit: true
        push: true

