apiVersion: apps/v1
kind: Deployment
metadata:
  name: k8s-test
spec:
  selector:
    matchLabels:
      app: k8s-test
  template:
    metadata:
      labels:
        app: k8s-test
    spec:
      containers:
        - name: k8s-test
          image: 52.14.78.29:5001/k8s-test
          imagePullPolicy: IfNotPresent
          resources:
            limits:
              memory: 256Mi
              cpu: 500m
          # ports:
            # - containerPort: 8080
      imagePullSecrets:
        - name: regcred
